duogaming/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('categorias/', views.CategoriaList.as_view(), name='categoria-list'),
    path('juegos/', views.JuegoList.as_view(), name='juego-list'),
]

duogaming/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('modificar/', views.modificar_usuario, name='modificar'),
]

duogaming/duogaming/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('games/', include('games.urls', namespace='games')),
    path('api/', include('api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

duogaming/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('nuevo/', views.nuevo_juego, name='nuevo'),
    path('eliminar/', views.eliminar_juego, name='eliminar_juego'),
    path('<str:nombre_categoria>/', views.categoria, name='categoria'),
]

duogaming/core/models.py
from django.db import models

# Create your models here.

duogaming/games/models.py
from django.db import models
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_delete

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)
    imagen = models.ImageField(upload_to='categoria_imagenes', blank=True, null=True)
    background = models.ImageField(upload_to='categoria_imagenes', blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    class Meta:
        ordering = ('nombre',)
    def __str__(self):
        return self.nombre
    def get_games_serialized(self):
        return [{"id": game.id, "nombre": game.nombre} for game in self.juegos.all()]

class Juego(models.Model):
    categoria = models.ForeignKey(Categoria, related_name = 'categoria', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True, null=True)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='juego_imagenes', blank=True, null=True)

    class Meta:
        ordering=('nombre', )

    def __str__(self):
        return self.nombre

    
def delete_juego_image(sender, instance, **kwargs):
    instance.imagen.delete(save=False)

post_delete.connect(delete_juego_image, sender=Juego)

duogaming/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
        username = forms.CharField(widget=forms.TextInput(attrs = {
        'placeholder': 'Nombre de usuario',
        'class': 'w-full py-3 px-4 rounded-xl',
        }))
        password = forms.CharField(widget=forms.PasswordInput(attrs = {
        'placeholder': 'Tu contraseña',
        'class': 'w-full py-3 px-4 rounded-xl',
        }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs = {
        'placeholder': 'Nombre de usuario',
        'class': 'w-full py-3 px-4 rounded-xl',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs = {
        'placeholder': 'Tu correo electrónico',
        'class': 'w-full py-3 px-4 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs = {
        'placeholder': 'Tu contraseña',
        'class': 'w-full py-3 px-4 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs = {
        'placeholder': 'Repite tu contraseña',
        'class': 'w-full py-3 px-4 rounded-xl',
    }))


class UpdateUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nombre de usuario',
        'class': 'w-full py-3 px-4 rounded-xl',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Tu correo electrónico',
        'class': 'w-full py-3 px-4 rounded-xl',
    }))

duogaming/core/views.py
from django.shortcuts import render, redirect
from games.models import Categoria, Juego
from .forms import SignupForm
from django.contrib import messages
# Create your views here.

def index(request):
    juegos = Juego.objects.all()
    categorias = Categoria.objects.all()


    return render(request, "core/index.html", {
        'categorias': categorias,
        'juegos': juegos,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UpdateUserForm


@login_required
def modificar_usuario(request):
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Se ha modificado al usuario')
            return redirect('/')  # replace 'some_view' with your desired redirect view
        else:
            messages.error(request, 'Error al modificar los datos')
    else:
        form = UpdateUserForm(instance=request.user)

    return render(request, 'core/modificar.html', {'form': form})

duogaming/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'core/styles.css' %}">
    <title> {%block title%}{%endblock%} | Duogaming</title>
</head >


<body >
    <nav class="py-6 px-6 flex justify-between items-center bg-gray-100" >
        <a href="/" class="text-xl font-semibold">Duogaming</a>

        <div class="space-x-6">
            {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                    <a href="{% url 'admin:index'  %}" class="text-lg font-semibold hover:text-gray-500">Administrar</a>
                {% endif %}
                
                {% if perms.games.add_juego %}
                    <a href="{% url 'games:nuevo'  %}" class="text-lg font-semibold hover:text-gray-500">Agregar Juego</a>
                {% endif %}
                {% if perms.games.delete_juego %}
                    <a href="{% url 'games:eliminar_juego'  %}" class="text-lg font-semibold hover:text-gray-500">Eliminar Juego</a>
                {% endif %}
            
            


                {% comment %} <a href="#" class="px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-teal-700">Carro</a> {% endcomment %}
                <a href="{% url 'core:modificar' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-blue-700">Usuario</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700">Cerrar sesión</a>
                <span class="text-gray-500">{{ request.user.username }}</span>
            {%else%}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-teal-700">Registrar</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Ingresar</a>
            {%endif%}
        </div>
    </nav>
    

    <div>
        {% block content %}
        {% endblock content %}
    </div>    


    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <p class="text-lg text-gray-500">DuoGaming 2023</p>
        </div>

         <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>
            <ul class="space-y-2">
                <li><a href="/" class="text-lg text-teal-500 hover:text-teal-700">Home</a></li>
                
            </ul>

         </div>
    </footer>













    <!-- Bootstrap CSS -->
   
</body>
</html>

duogaming/core/templates/core/contact.html
{% extends 'core/base.html' %}

duogaming/core/templates/core/index.html
{% extends 'core/base.html' %}

{%block title%} Welcome {%endblock  %}

{% block content %}
    <div class="category-background" style="background-image: url('/media/index_imagenes/deathwing.jpg')">
        <div class="category-name">Categorías</div>
    </div>
    <div class="px-6 py-12 bg-gray-200">
        <div class="grid grid-cols-5 gap-10">
            {%for categoria in categorias%}
                <div style="box-shadow: 0px 4px 30px 0px black; border-radius: 10px;">
                    <a href="{% url 'games:categoria' categoria.nombre %}">
                        <div >
                            <img src="{{ categoria.imagen.url }}" class="rounded-t-xl" >
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ categoria.nombre }} </h2>
                            <p class="text-gray-500"> {{ categoria.descripcion }}</p>
                        </div>

                    </a>
                </div>
            {%endfor%}
        </div>
    </div>


{% endblock content %}

duogaming/core/templates/core/login.html
{%extends 'core/base.html' %}

{% block title%}Ingresar{% endblock %}


{% block content %}
    <div class="w-1/2 my-12 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Ingresar</h2>

        <form method="post" action=".">
            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Usuario</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Contraseña</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}

                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}


            <button class="py-4 px-8 txt-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>

        </form>

    </div>

{% endblock content %}
    

duogaming/core/templates/core/modificar.html
{%extends 'core/base.html' %}

{% block title%}Modificar{% endblock %}


{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Modificar</h2>

        <form method="post" action=".">
            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Usuario</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}

                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}


            <button class="py-4 px-8 txt-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Modificar datos</button>

        </form>

    </div>
{% endblock content %}
    

duogaming/core/templates/core/signup.html
{%extends 'core/base.html' %}

{% block title%}Registrar{% endblock %}


{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Registrar</h2>

        <form method="post" action=".">
            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Usuario</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Contraseña</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Repetir contraseña</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}

                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}


            <button class="py-4 px-8 txt-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>

        </form>

    </div>
{% endblock content %}
    